In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import requests
import gmaps
import os
from pprint import pprint
from api_keys import gkey #api key

In [2]:
# load up the data
cityWeather = pd.read_csv('../WeatherPy/output_data/cities.csv', index_col=False)

# Rename index
cityWeather = cityWeather.set_index('Unnamed: 0')
cityWeather = cityWeather.rename_axis('index')

# length of list
print(f"The number of cities on the list is: {len(cityWeather)}")

The number of cities on the list is: 546

In [3]:
cityWeather.head()

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
index,,,,,,,,,
0,Ushuaia,-54.8000,-68.3000,38.82,64,20,6.91,AR,1658868434
1,Arraial do Cabo,-22.9661,-42.0278,73.36,78,0,14.97,BR,1658868253
2,Orlik,52.5178,99.8250,42.64,84,68,0.72,RU,1658868434
3,Mataura,-46.1927,168.8643,44.47,97,100,7.02,NZ,1658868435
4,Chapada dos Guimarães,-15.4606,-55.7497,87.46,22,5,2.98,BR,1658868435

## Humidity Heatmap|

In [4]:
#Config gmaps
gmaps.configure(api_key=gkey)

In [5]:
# Store latitude and longitude for locations and humidity for weight
locations = cityWeather[['Lat', 'Lng']].astype(float)
weight = cityWeather['Humidity'].astype(float)

# Plot Heatmap
fig = gmaps.figure()

# Create heat layer
heatLayer = gmaps.heatmap_layer(locations, weights = weight, dissipating=False, max_intensity=100, point_radius=1)

# Add layer
fig.add_layer(heatLayer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

In [11]:
# Drop rows with NaN values
cityWeather = cityWeather.dropna()

# Ideal weather conditions to narrow down data
cityWeatherFix = cityWeather[cityWeather['Max Temp'] < 80]
cityWeatherFix = cityWeatherFix[cityWeatherFix['Max Temp'] > 70]
cityWeatherFix = cityWeatherFix[cityWeatherFix['Wind Speed'] < 10]
cityWeatherFix = cityWeatherFix[cityWeatherFix['Cloudiness'] == 0]
cityWeatherFix

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
index,,,,,,,,,
20,Dzaoudzi,-12.7887,45.2699,73.29,78,0,9.22,YT,1658868439
81,Qaraçala,39.8132,48.9523,74.88,65,0,4.94,AZ,1658868460
254,Nahariya,33.0059,35.0941,73.98,88,0,2.13,IL,1658868526
293,Esmeraldas,-19.7625,-44.3139,75.31,41,0,3.58,BR,1658868543
299,Methóni,36.8197,21.7049,73.26,68,0,4.32,GR,1658868544
303,Arak,34.0917,49.6892,76.87,36,0,2.24,IR,1658868546
315,Goderich,43.7501,-81.7165,74.91,46,0,6.91,CA,1658868549
321,Mackenzie,55.2999,-123.1698,79.02,47,0,4.61,CA,1658868369
327,Slave Lake,55.2834,-114.7690,71.58,49,0,4.61,CA,1658868375
390,Tūkrah,32.5341,20.5791,79.45,78,0,3.56,LY,1658868581
393,Wajima,37.4000,136.9000,76.48,85,0,3.42,JP,1658868340
472,Cangzhou,38.3167,116.8667,75.09,79,0,5.59,CN,1658868411
497,Great Falls,47.5002,-111.3008,79.68,45,0,5.75,US,1658868627
531,Nishihara,26.1842,127.7558,78.08,94,0,3.44,JP,1658868638
534,Zhangaözen,43.3000,52.8000,76.73,48,0,7.90,KZ,1658868638

### Hotel Map

In [14]:
hotelDF = cityWeatherFix

# Add columns to store hotel data
hotelDF['Hotel Name'] = ""
hotelDF['Hotel Lat'] = ""
hotelDF['Hotel Lon'] = ""
hotelDF

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name,Hotel Lat,Hotel Lon
index,,,,,,,,,,,,
20,Dzaoudzi,-12.7887,45.2699,73.29,78,0,9.22,YT,1658868439,,,
81,Qaraçala,39.8132,48.9523,74.88,65,0,4.94,AZ,1658868460,,,
254,Nahariya,33.0059,35.0941,73.98,88,0,2.13,IL,1658868526,,,
293,Esmeraldas,-19.7625,-44.3139,75.31,41,0,3.58,BR,1658868543,,,
299,Methóni,36.8197,21.7049,73.26,68,0,4.32,GR,1658868544,,,
303,Arak,34.0917,49.6892,76.87,36,0,2.24,IR,1658868546,,,
315,Goderich,43.7501,-81.7165,74.91,46,0,6.91,CA,1658868549,,,
321,Mackenzie,55.2999,-123.1698,79.02,47,0,4.61,CA,1658868369,,,
327,Slave Lake,55.2834,-114.7690,71.58,49,0,4.61,CA,1658868375,,,
390,Tūkrah,32.5341,20.5791,79.45,78,0,3.56,LY,1658868581,,,
393,Wajima,37.4000,136.9000,76.48,85,0,3.42,JP,1658868340,,,
472,Cangzhou,38.3167,116.8667,75.09,79,0,5.59,CN,1658868411,,,
497,Great Falls,47.5002,-111.3008,79.68,45,0,5.75,US,1658868627,,,
531,Nishihara,26.1842,127.7558,78.08,94,0,3.44,JP,1658868638,,,
534,Zhangaözen,43.3000,52.8000,76.73,48,0,7.90,KZ,1658868638,,,

In [16]:
# params dictionary for each iteration to retrieve data
params = {
    "radius": 5000,
    "keyword": "hotel",
    "key": gkey
}

# For loop will identify nearby hotels using lat/lng of narrowed down cities
for column, row in hotelDF.iterrows():
    print(f"Retrieving Hotel Data for {row['City']}, {row['Country']}.")
    
    # Retrieve lat and lng from dataframe
    lat = row['Lat']
    lng = row['Lng']
    
    # Uses new location lat and lng during each iteration
    params["location"] = f"{lat},{lng}"
    
    # Make API call to retrieve data from Google Maps API
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    name_address = requests.get(base_url, params=params).json()
    
    try:
        print(f"Closest Hotel is {name_address['results'][0]['name']}")
        
        hotelDF.loc[column, 'Hotel Name'] = name_address['results'][0]['name']
        hotelDF.loc[column, 'Hotel Lat'] = name_address['results'][0]['geometry']['location']['lat']
        hotelDF.loc[column, 'Hotel Lon'] = name_address['results'][0]['geometry']['location']['lng']
    except (KeyError, IndexError):
        print("No hotel found within radius. Skipping...")
        hotelDF.loc[column, 'Hotel Name'] = np.NaN
        hotelDF.loc[column, 'Hotel Lat'] = np.NaN
        hotelDF.loc[column, 'Hotel Lon'] = np.NaN
        
    print(f"Data processing for {row['City']}, {row['Country']} is complete")


hotelDF

Retrieving Hotel Data for Dzaoudzi, YT.
Closest Hotel is Hotel Maharajah Mayotte
Data processing for Dzaoudzi, YT is complete
Retrieving Hotel Data for Qaraçala, AZ.
Closest Hotel is Qaraçala
Data processing for Qaraçala, AZ is complete
Retrieving Hotel Data for Nahariya, IL.
Closest Hotel is Sea Life Spa Hotel
Data processing for Nahariya, IL is complete
Retrieving Hotel Data for Esmeraldas, BR.
Closest Hotel is Parque do Avestruz Eco Resort
Data processing for Esmeraldas, BR is complete
Retrieving Hotel Data for Methóni, GR.
Closest Hotel is CARLOS MANSION LUXURY SUITES
Data processing for Methóni, GR is complete
Retrieving Hotel Data for Arak, IR.
Closest Hotel is اراک
Data processing for Arak, IR is complete
Retrieving Hotel Data for Goderich, CA.
Closest Hotel is Samuels Hotel
Data processing for Goderich, CA is complete
Retrieving Hotel Data for Mackenzie, CA.
Closest Hotel is Royal Oak Inn & Suites & RV Park
Data processing for Mackenzie, CA is complete
Retrieving Hotel Data for Slave Lake, CA.
Closest Hotel is Holiday Inn Express & Suites Slave Lake, an IHG Hotel
Data processing for Slave Lake, CA is complete
Retrieving Hotel Data for Tūkrah, LY.
Closest Hotel is مصيف مرحبا للعائلات
Data processing for Tūkrah, LY is complete
Retrieving Hotel Data for Wajima, JP.
Closest Hotel is Hotel Route-Inn Wajima
Data processing for Wajima, JP is complete
Retrieving Hotel Data for Cangzhou, CN.
Closest Hotel is King Lion International Hotel
Data processing for Cangzhou, CN is complete
Retrieving Hotel Data for Great Falls, US.
Closest Hotel is Hotel Arvon
Data processing for Great Falls, US is complete
Retrieving Hotel Data for Nishihara, JP.
Closest Hotel is YAESE HOTEL
Data processing for Nishihara, JP is complete
Retrieving Hotel Data for Zhangaözen, KZ.
Closest Hotel is Hotel BasTau
Data processing for Zhangaözen, KZ is complete

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name,Hotel Lat,Hotel Lon
index,,,,,,,,,,,,
20,Dzaoudzi,-12.7887,45.2699,73.29,78,0,9.22,YT,1658868439,Hotel Maharajah Mayotte,-12.782308,45.229767
81,Qaraçala,39.8132,48.9523,74.88,65,0,4.94,AZ,1658868460,Qaraçala,39.808186,48.935672
254,Nahariya,33.0059,35.0941,73.98,88,0,2.13,IL,1658868526,Sea Life Spa Hotel,33.025233,35.094492
293,Esmeraldas,-19.7625,-44.3139,75.31,41,0,3.58,BR,1658868543,Parque do Avestruz Eco Resort,-19.771548,-44.352373
299,Methóni,36.8197,21.7049,73.26,68,0,4.32,GR,1658868544,CARLOS MANSION LUXURY SUITES,36.825905,21.710647
303,Arak,34.0917,49.6892,76.87,36,0,2.24,IR,1658868546,اراک,34.097106,49.715887
315,Goderich,43.7501,-81.7165,74.91,46,0,6.91,CA,1658868549,Samuels Hotel,43.752127,-81.69779
321,Mackenzie,55.2999,-123.1698,79.02,47,0,4.61,CA,1658868369,Royal Oak Inn & Suites & RV Park,55.331424,-123.095349
327,Slave Lake,55.2834,-114.7690,71.58,49,0,4.61,CA,1658868375,"Holiday Inn Express & Suites Slave Lake, an IH...",55.270859,-114.781101
390,Tūkrah,32.5341,20.5791,79.45,78,0,3.56,LY,1658868581,مصيف مرحبا للعائلات,32.569375,20.628043
393,Wajima,37.4000,136.9000,76.48,85,0,3.42,JP,1658868340,Hotel Route-Inn Wajima,37.396057,136.904983
472,Cangzhou,38.3167,116.8667,75.09,79,0,5.59,CN,1658868411,King Lion International Hotel,38.304909,116.81352
497,Great Falls,47.5002,-111.3008,79.68,45,0,5.75,US,1658868627,Hotel Arvon,47.504013,-111.305099
531,Nishihara,26.1842,127.7558,78.08,94,0,3.44,JP,1658868638,YAESE HOTEL,26.152559,127.721698
534,Zhangaözen,43.3000,52.8000,76.73,48,0,7.90,KZ,1658868638,Hotel BasTau,43.33735,52.85714

In [20]:
# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotelDF.iterrows()]
locations = hotelDF[["Hotel Lat", "Hotel Lon"]]

In [23]:
weight = hotelDF["Humidity"]

# Plot Heatmap
fig = gmaps.figure()

# Create heat layer
markers = gmaps.marker_layer(locations, info_box_content=hotel_info)
heat_layer = gmaps.heatmap_layer(locations, weights = weight, dissipating=False, max_intensity=100, point_radius=1)

# Add layer
fig.add_layer(heatLayer)
fig.add_layer(markers)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))